### ISSUE TITLE
Feature request: support setting DNS entries

### ISSUE THREAD

**Issue by chloe-the-catgirl** [inwx/terraform-provider-inwx#2]
While setting customer information and several information for domains is possible, there's no way for setting DNS entries for specific domains yet. 

I know that there's the [Hashicorp DNS module](https://registry.terraform.io/providers/hashicorp/dns/latest/docs), but unfortunately I couldn't find any information whether INWX supports it or not.

**Comment by JohannesRudolph** [comment]
Looks like it's in the API but not in the terraform provider - would be cool to add this.

**Comment by lucendio** [comment]
FYI: atm I'm using https://github.com/andrexus/terraform-provider-inwx but a) it's outdated and b) it does not really honor the Terraform state and thus always re-applies all entries to all managed zones.

**Comment by hikhvar** [comment]
@lucendio did you manage to get the andrexus provider work with terraform versions above v0.12.? 

And I really really would like to have this feature added. From my point of view, only with this feature, this provider is of any use for me as an user. I manage many more DNS records, than domain names.

**Comment by waeltken** [comment]
Looks like #1 solves this issue. This would allow to use inwx in combination with the [Hashicorp DNS module](https://registry.terraform.io/providers/hashicorp/dns/latest/docs).

**Comment by hikhvar** [comment]
I would like to have an easy way to update my DNS records via terraform, without enrolling DNSSEC on my domains. INWX offers this method via their API. I would like to use that mechanism.

**Comment by lucendio** [comment]
> did you manage to get the andrexus provider work with terraform versions above v0.12.?

@hikhvar I'm running it with Terraform `1.1.9`. What kind of issue do you face with newer versions of Terraform and the *andrexus* provider?

> Looks like https://github.com/inwx/terraform-provider-inwx/pull/1 solves this issue. This would allow to use inwx in combination with the [Hashicorp DNS module](https://registry.terraform.io/providers/hashicorp/dns/latest/docs).

@waeltken just to clarify, because I have little knowledge on the matter: are you saying that https://github.com/inwx/terraform-provider-inwx/pull/1 would enable [RFC2845 (TSIG)](https://www.rfc-editor.org/rfc/rfc2845), therefore the usage of Hashicorp's [DNS Provider](https://registry.terraform.io/providers/hashicorp/dns/latest/docs#example-usage) (as sort of a 2-stage approach) to archive the missing functionality mentioned above?

**Comment by fsoederhuyzen** [comment]
#1 has been merged since 1.1.0
#5 (which has been merged since 1.2.0) resolves setting nameserver records via the api (without DNSSEC)
It is now possible to use the new [`inwx_nameserver_record`](https://github.com/inwx/terraform-provider-inwx/blob/main/docs/resources/inwx_nameserver_record.md) resource to set dns entries.
